In [1]:
import sklearn
sklearn.__version__

'1.4.2'

# 

# Preprocessing

## Ordinal Encoding

In [2]:
from sklearn.preprocessing import OrdinalEncoder

In [3]:
encoder = OrdinalEncoder()

In [10]:
X = [['B'], ['A'], ['C'], ['D']]

In [11]:
encoder.fit(X)

OrdinalEncoder()

In [12]:
X_ = encoder.transform(X)

In [13]:
X_

array([[1.],
       [0.],
       [2.],
       [3.]])

In [14]:
encoder.categories_

[array(['A', 'B', 'C', 'D'], dtype=object)]

In [15]:
X = [['A', 10], ['B', 9.5], ['C', 8], ['D', 16]]

In [16]:
encoder.fit(X)

OrdinalEncoder()

In [17]:
X_ = encoder.transform(X)

In [18]:
X_

array([[0., 2.],
       [1., 1.],
       [2., 0.],
       [3., 3.]])

In [19]:
encoder.categories_

[array(['A', 'B', 'C', 'D'], dtype=object),
 array([8, 9.5, 10, 16], dtype=object)]

In [20]:
encoder.inverse_transform(X_)

array([['A', 10],
       ['B', 9.5],
       ['C', 8],
       ['D', 16]], dtype=object)

# Label Encoder

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
encoder = LabelEncoder()

In [36]:
Y = ['bat', 'ant', 'cat', 'dog', 'ant']

In [37]:
encoder.fit(Y)

LabelEncoder()

In [38]:
Y_ = encoder.transform(Y)

In [39]:
Y_

array([1, 0, 2, 3, 0])

In [40]:
encoder.classes_

array(['ant', 'bat', 'cat', 'dog'], dtype='<U3')

In [41]:
encoder.inverse_transform(Y_)

array(['bat', 'ant', 'cat', 'dog', 'ant'], dtype='<U3')

# One-hot Encoding

In [42]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
encoder = OneHotEncoder()

In [44]:
X = [['ant'], ['bat'], ['cat'], ['bat'], ['ant'], ['cat']]

In [45]:
encoder.fit(X)

OneHotEncoder()

In [46]:
X_ = encoder.transform(X)

In [47]:
X_

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [48]:
X_.todense()

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]])

In [49]:
encoder.categories_

[array(['ant', 'bat', 'cat'], dtype=object)]

In [50]:
encoder.inverse_transform(X_)

array([['ant'],
       ['bat'],
       ['cat'],
       ['bat'],
       ['ant'],
       ['cat']], dtype=object)

In [51]:
import pandas as pd

In [52]:
df = pd.DataFrame(X, columns=['animal'])

In [53]:
df

animal
0    ant
1    bat
2    cat
3    bat
4    ant
5    cat

In [54]:
pd.get_dummies(df)

animal_ant  animal_bat  animal_cat
0        True       False       False
1       False        True       False
2       False       False        True
3       False        True       False
4        True       False       False
5       False       False        True

In [55]:
pd.get_dummies(df, dtype=int)

animal_ant  animal_bat  animal_cat
0           1           0           0
1           0           1           0
2           0           0           1
3           0           1           0
4           1           0           0
5           0           0           1

In [56]:
df = pd.DataFrame([['male'], ['female'], ['female'], ['male']], columns=['gender'])

In [58]:
df_ = pd.get_dummies(df, dtype=int)

In [59]:
df_.columns

Index(['gender_female', 'gender_male'], dtype='object')

In [60]:
df_.drop(columns=df_.columns[0])

gender_male
0            1
1            0
2            0
3            1